### ISSUE TITLE
future pomp release is blocked pending update of spatPomp

### ISSUE THREAD

**Issue by kingaa** [kidusasfaw/spatPomp#20]
Hi @kidusasfaw , Hi @ionides:

In an upcoming release of **pomp**, the `set_pomp_userdata` and `unset_pomp_userdata` functions, which no longer serve any purpose, will be removed.  This breaks the existing CRAN version of **spatPomp** (0.33.0), but is fixed in the current version on Github.  Please consider releasing a new version of **spatPomp** to CRAN so that this change in **pomp** can go forward.

**Comment by kidusasfaw** [comment]
Hi all,

Good to hear from you, Aaron. Thank you for the updates to spatpomp in GitHub.

Hi Ed, 
I hope all is well with you. What do you think of this? I don’t think I am able to upload a new version given I’m no longer a maintainer. I can give it a try but it might take me a little time to set things up with my new computer (Probably early Jan timeline).Hope you two are able to see the finish line of the semester on the horizon.

Sent from my iPhone

On Dec 2, 2023, at 7:18 AM, Aaron A King ***@***.***> wrote:﻿
Hi @kidusasfaw , Hi @ionides:
In an upcoming release of pomp, the set_pomp_userdata and unset_pomp_userdata functions, which no longer serve any purpose, will be removed.  This breaks the existing CRAN version of spatPomp (0.33.0), but is fixed in the current version on Github.  Please consider releasing a new version of spatPomp to CRAN so that this change in pomp can go forward.

**Comment by ionides** [comment]
Hi Aaron, Thanks for doing this. I will push to CRAN shortly. There have
been a few other small updates since I last pushed to CRAN on Jul 28, so
it's time to update that. Best, Ed.

**Comment by kingaa** [comment]
If you want to check to make sure it will work with future version of **pomp**, you can check it against [the `deprec` branch](https://github.com/kingaa/pomp/tree/deprec).
